name: ci

on:
  pull_request:
    paths:
      - ".github/workflows/quality.yml"
      - "flake.lock"
      - "flake.nix"
      - "**/*.sh"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y shellcheck

      - name: Check shell scripts
        run: git ls-files -z '*.sh' | xargs -0 shellcheck

  nix:
    name: nix-flake-check
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Enable Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check flake
        run: nix flake check --no-update-lock-file
